language: dart

dart:
# Install the latest stable release
- stable

dart_task:
- test: --platform vm

# As long as you don't want any other configuration, you can just use the name of a task instead of "name: true".
- test

#To run the Dart analyzer to verify that your code doesn’t have any static errors. 
#By default it analyzes all Dart files in your repository, but you can configure it by providing arguments instead of true.
#- dartanalyzer: --fatal-warnings lib

#To run the Dart formatter to verify that all your files are correctly formatted
#- dartfmt
