language: dart
addons:
  apt:
    packages:
      - lib32stdc++6
env:
  global:
    - FLUTTER_CHANNEL=stable
install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - cd RasPiFinder/ && flutter packages get
cache:
  directories:
    - $HOME/.pub-cache

static_analysis: &static_analysis
  name: "Static analysis"
  script: flutter analyze

unit_tests: &unit_tests
  name: "Unit tests"
  #script: flutter test test/unit_test.dart

widget_tests: &widget_tests
  name: "Widget tests"
  script: flutter test test/widget_test.dart

integration_tests: &integration_tests
  name: "Integration tests"
  #script: flutter drive --target=test_driver/main.dart

jobs:
  include:
  - <<: *static_analysis
  - <<: *unit_tests
  - <<: *widget_tests
  - <<: *integration_tests
  - stage: build
  - stage: deploy

# stages:
  # - compile
  # - test
  # - build
  # - name: deploy
    # if: branch = master
